require 'sfml'

do print '# Time'
	local t: sfml.Time = sfml.Time.zero
	local ms = t:asMilliseconds()
	local sec = t:asSeconds()
	print(ms, sec)
end

do print '\n## Clock'
	local c: *sfml.Clock = sfml.Clock.create()
	defer c:destroy() end

	print(c:getElapsedTime():asSeconds())
	print(c:getElapsedTime():asMilliseconds())
end

do print '\n# Threads'
	local function thing(ptr: pointer)
		for i=0, 20 do
			print(i)
		end
	end

	local t: *sfml.Thread = sfml.Thread.create(thing, nilptr)
	defer t:destroy() end

	t:launch()
	t:wait()
end

do print '\n# Vectors'
	local vi = sfml.Vector2i{1, 2}
	print(vi.x, vi.y)
	
	local vu = sfml.Vector2u{1, 2}
	print(vu.x, vu.y)

	local vf = sfml.Vector2f{1, 2}
	print(vf.x, vf.y)

	local v3 = sfml.Vector3f{1, 2, 3}
	print(v3.x, v3.y, v3.z)
end

do print '# Window'
	local window = sfml.Window.create((@sfml.VideoMode){720, 480, 32}, "Hello", sfml.DefaultStyle, nilptr)
	defer window:destroy() end
end