require 'sfml'

do print '# Time'
	local t: sfml.Time = sfml.Time.zero
	local ms = t:asMilliseconds()
	local sec = t:asSeconds()
	print(ms, sec)
end

do print '## Clock'
	local c: *sfml.Clock = sfml.Clock.create()
	defer c:destroy() end

	print(c:getElapsedTime():asSeconds())
	print(c:getElapsedTime():asMilliseconds())
end

do print '# Threads'
	local function thing(ptr: pointer)
		for i=0, 100 do
			print(i)
		end
	end

	local t: *sfml.Thread = sfml.Thread.create(thing, nilptr)
	defer t:destroy() end

	t:launch()
	t:wait()
end